development: &defaults
  :facebook:
    :app_id: '237759266807516'
    :app_secret: 'fa377dad0077f22b0f4e17651d142ff9'
  :twitter:
    :api_id: '8tY1BrpKJfFjEAu1zd4vHhXml'                                                                                                                                                        
    :api_secret: 'XPQ50ksKPliwiSaB3yrxJ4OrYzhWk2Ul69IJBaUpBE7YXypy87'

test:
  <<: *defaults

production:
  <<: *defaults
  